/**
 * Books Configuration
 * Curated list of 200 famous books and book selection utilities
 */

/**
 * Famous Books Library
 * Curated list of 200 famous books from the past 30 years
 */
export const FAMOUS_BOOKS = [
    { title: "Harry Potter and the Sorcerer's Stone", author: "J.K. Rowling" },
    { title: "Harry Potter and the Chamber of Secrets", author: "J.K. Rowling" },
    { title: "Harry Potter and the Prisoner of Azkaban", author: "J.K. Rowling" },
    { title: "Harry Potter and the Goblet of Fire", author: "J.K. Rowling" },
    { title: "Harry Potter and the Order of the Phoenix", author: "J.K. Rowling" },
    { title: "Harry Potter and the Half-Blood Prince", author: "J.K. Rowling" },
    { title: "Harry Potter and the Deathly Hallows", author: "J.K. Rowling" },
    { title: "The Hunger Games", author: "Suzanne Collins" },
    { title: "Catching Fire", author: "Suzanne Collins" },
    { title: "Mockingjay", author: "Suzanne Collins" },
    { title: "The Da Vinci Code", author: "Dan Brown" },
    { title: "Angels & Demons", author: "Dan Brown" },
    { title: "Inferno", author: "Dan Brown" },
    { title: "The Kite Runner", author: "Khaled Hosseini" },
    { title: "A Thousand Splendid Suns", author: "Khaled Hosseini" },
    { title: "Life of Pi", author: "Yann Martel" },
    { title: "The Lovely Bones", author: "Alice Sebold" },
    { title: "The Help", author: "Kathryn Stockett" },
    { title: "The Girl with the Dragon Tattoo", author: "Stieg Larsson" },
    { title: "The Girl Who Played with Fire", author: "Stieg Larsson" },
    { title: "The Girl Who Kicked the Hornet's Nest", author: "Stieg Larsson" },
    { title: "Gone Girl", author: "Gillian Flynn" },
    { title: "Sharp Objects", author: "Gillian Flynn" },
    { title: "The Fault in Our Stars", author: "John Green" },
    { title: "Looking for Alaska", author: "John Green" },
    { title: "Paper Towns", author: "John Green" },
    { title: "Twilight", author: "Stephenie Meyer" },
    { title: "New Moon", author: "Stephenie Meyer" },
    { title: "Eclipse", author: "Stephenie Meyer" },
    { title: "Breaking Dawn", author: "Stephenie Meyer" },
    { title: "The Road", author: "Cormac McCarthy" },
    { title: "No Country for Old Men", author: "Cormac McCarthy" },
    { title: "Atonement", author: "Ian McEwan" },
    { title: "Cloud Atlas", author: "David Mitchell" },
    { title: "The Book Thief", author: "Markus Zusak" },
    { title: "Water for Elephants", author: "Sara Gruen" },
    { title: "The Time Traveler's Wife", author: "Audrey Niffenegger" },
    { title: "The Secret Life of Bees", author: "Sue Monk Kidd" },
    { title: "Memoirs of a Geisha", author: "Arthur Golden" },
    { title: "American Gods", author: "Neil Gaiman" },
    { title: "Coraline", author: "Neil Gaiman" },
    { title: "The Ocean at the End of the Lane", author: "Neil Gaiman" },
    { title: "Good Omens", author: "Neil Gaiman and Terry Pratchett" },
    { title: "A Game of Thrones", author: "George R.R. Martin" },
    { title: "A Clash of Kings", author: "George R.R. Martin" },
    { title: "A Storm of Swords", author: "George R.R. Martin" },
    { title: "A Feast for Crows", author: "George R.R. Martin" },
    { title: "A Dance with Dragons", author: "George R.R. Martin" },
    { title: "The Martian", author: "Andy Weir" },
    { title: "Project Hail Mary", author: "Andy Weir" },
    { title: "Ready Player One", author: "Ernest Cline" },
    { title: "Ready Player Two", author: "Ernest Cline" },
    { title: "The Name of the Wind", author: "Patrick Rothfuss" },
    { title: "The Wise Man's Fear", author: "Patrick Rothfuss" },
    { title: "The Night Circus", author: "Erin Morgenstern" },
    { title: "The Goldfinch", author: "Donna Tartt" },
    { title: "The Secret History", author: "Donna Tartt" },
    { title: "All the Light We Cannot See", author: "Anthony Doerr" },
    { title: "The Light Between Oceans", author: "M.L. Stedman" },
    { title: "Room", author: "Emma Donoghue" },
    { title: "Big Little Lies", author: "Liane Moriarty" },
    { title: "The Husband's Secret", author: "Liane Moriarty" },
    { title: "Wild", author: "Cheryl Strayed" },
    { title: "Educated", author: "Tara Westover" },
    { title: "Becoming", author: "Michelle Obama" },
    { title: "The Glass Castle", author: "Jeannette Walls" },
    { title: "Unbroken", author: "Laura Hillenbrand" },
    { title: "The Immortal Life of Henrietta Lacks", author: "Rebecca Skloot" },
    { title: "Into the Wild", author: "Jon Krakauer" },
    { title: "Into Thin Air", author: "Jon Krakauer" },
    { title: "The Devil in the White City", author: "Erik Larson" },
    { title: "In Cold Blood", author: "Truman Capote" },
    { title: "Divergent", author: "Veronica Roth" },
    { title: "Insurgent", author: "Veronica Roth" },
    { title: "Allegiant", author: "Veronica Roth" },
    { title: "The Maze Runner", author: "James Dashner" },
    { title: "The Scorch Trials", author: "James Dashner" },
    { title: "The Death Cure", author: "James Dashner" },
    { title: "The Perks of Being a Wallflower", author: "Stephen Chbosky" },
    { title: "Thirteen Reasons Why", author: "Jay Asher" },
    { title: "Eleanor & Park", author: "Rainbow Rowell" },
    { title: "The 5th Wave", author: "Rick Yancey" },
    { title: "Miss Peregrine's Home for Peculiar Children", author: "Ransom Riggs" },
    { title: "Everything, Everything", author: "Nicola Yoon" },
    { title: "The Sun is Also a Star", author: "Nicola Yoon" },
    { title: "Me Before You", author: "Jojo Moyes" },
    { title: "Still Alice", author: "Lisa Genova" },
    { title: "The Notebook", author: "Nicholas Sparks" },
    { title: "A Walk to Remember", author: "Nicholas Sparks" },
    { title: "The Lucky One", author: "Nicholas Sparks" },
    { title: "Safe Haven", author: "Nicholas Sparks" },
    { title: "The Longest Ride", author: "Nicholas Sparks" },
    { title: "The Handmaid's Tale", author: "Margaret Atwood" },
    { title: "The Testaments", author: "Margaret Atwood" },
    { title: "Oryx and Crake", author: "Margaret Atwood" },
    { title: "The Poisonwood Bible", author: "Barbara Kingsolver" },
    { title: "Beloved", author: "Toni Morrison" },
    { title: "A Thousand Acres", author: "Jane Smiley" },
    { title: "The Amazing Adventures of Kavalier & Clay", author: "Michael Chabon" },
    { title: "The Corrections", author: "Jonathan Franzen" },
    { title: "Freedom", author: "Jonathan Franzen" },
    { title: "Middlesex", author: "Jeffrey Eugenides" },
    { title: "The Virgin Suicides", author: "Jeffrey Eugenides" },
    { title: "White Teeth", author: "Zadie Smith" },
    { title: "The Namesake", author: "Jhumpa Lahiri" },
    { title: "Interpreter of Maladies", author: "Jhumpa Lahiri" },
    { title: "Bel Canto", author: "Ann Patchett" },
    { title: "The Poisonwood Bible", author: "Barbara Kingsolver" },
    { title: "Snow Falling on Cedars", author: "David Guterson" },
    { title: "The Curious Incident of the Dog in the Night-Time", author: "Mark Haddon" },
    { title: "Never Let Me Go", author: "Kazuo Ishiguro" },
    { title: "The Remains of the Day", author: "Kazuo Ishiguro" },
    { title: "The Underground Railroad", author: "Colson Whitehead" },
    { title: "The Nickel Boys", author: "Colson Whitehead" },
    { title: "Homegoing", author: "Yaa Gyasi" },
    { title: "The Hate U Give", author: "Angie Thomas" },
    { title: "The Nightingale", author: "Kristin Hannah" },
    { title: "The Great Alone", author: "Kristin Hannah" },
    { title: "Where the Crawdads Sing", author: "Delia Owens" },
    { title: "Circe", author: "Madeline Miller" },
    { title: "The Song of Achilles", author: "Madeline Miller" },
    { title: "The Seven Husbands of Evelyn Hugo", author: "Taylor Jenkins Reid" },
    { title: "Daisy Jones & The Six", author: "Taylor Jenkins Reid" },
    { title: "Malibu Rising", author: "Taylor Jenkins Reid" },
    { title: "The Midnight Library", author: "Matt Haig" },
    { title: "Anxious People", author: "Fredrik Backman" },
    { title: "A Man Called Ove", author: "Fredrik Backman" },
    { title: "Beartown", author: "Fredrik Backman" },
    { title: "The Thursday Murder Club", author: "Richard Osman" },
    { title: "The Man Who Died Twice", author: "Richard Osman" },
    { title: "The Silent Patient", author: "Alex Michaelides" },
    { title: "The Maidens", author: "Alex Michaelides" },
    { title: "The Woman in the Window", author: "A.J. Finn" },
    { title: "The Guest List", author: "Lucy Foley" },
    { title: "The Hunting Party", author: "Lucy Foley" },
    { title: "Then She Was Gone", author: "Lisa Jewell" },
    { title: "The Family Upstairs", author: "Lisa Jewell" },
    { title: "Little Fires Everywhere", author: "Celeste Ng" },
    { title: "Everything I Never Told You", author: "Celeste Ng" },
    { title: "The Dutch House", author: "Ann Patchett" },
    { title: "Commonwealth", author: "Ann Patchett" },
    { title: "A Gentleman in Moscow", author: "Amor Towles" },
    { title: "Rules of Civility", author: "Amor Towles" },
    { title: "The Lincoln Highway", author: "Amor Towles" },
    { title: "The Invisible Life of Addie LaRue", author: "V.E. Schwab" },
    { title: "The Ten Thousand Doors of January", author: "Alix E. Harrow" },
    { title: "The Starless Sea", author: "Erin Morgenstern" },
    { title: "The Priory of the Orange Tree", author: "Samantha Shannon" },
    { title: "The Fifth Season", author: "N.K. Jemisin" },
    { title: "The Obelisk Gate", author: "N.K. Jemisin" },
    { title: "The Stone Sky", author: "N.K. Jemisin" },
    { title: "Children of Blood and Bone", author: "Tomi Adeyemi" },
    { title: "Children of Virtue and Vengeance", author: "Tomi Adeyemi" },
    { title: "An American Marriage", author: "Tayari Jones" },
    { title: "The Vanishing Half", author: "Brit Bennett" },
    { title: "Such a Fun Age", author: "Kiley Reid" },
    { title: "Pachinko", author: "Min Jin Lee" },
    { title: "The Overstory", author: "Richard Powers" },
    { title: "There There", author: "Tommy Orange" },
    { title: "The Water Dancer", author: "Ta-Nehisi Coates" },
    { title: "Between the World and Me", author: "Ta-Nehisi Coates" },
    { title: "Born a Crime", author: "Trevor Noah" },
    { title: "Sapiens", author: "Yuval Noah Harari" },
    { title: "Homo Deus", author: "Yuval Noah Harari" },
    { title: "21 Lessons for the 21st Century", author: "Yuval Noah Harari" },
    { title: "The Power of Habit", author: "Charles Duhigg" },
    { title: "Thinking, Fast and Slow", author: "Daniel Kahneman" },
    { title: "Quiet", author: "Susan Cain" },
    { title: "The Lean Startup", author: "Eric Ries" },
    { title: "The 4-Hour Workweek", author: "Timothy Ferriss" },
    { title: "Steve Jobs", author: "Walter Isaacson" },
    { title: "Shoe Dog", author: "Phil Knight" },
    { title: "When Breath Becomes Air", author: "Paul Kalanithi" },
    { title: "Being Mortal", author: "Atul Gawande" },
    { title: "The Sixth Extinction", author: "Elizabeth Kolbert" },
    { title: "Bad Blood", author: "John Carreyrou" },
    { title: "Hillbilly Elegy", author: "J.D. Vance" },
    { title: "Just Mercy", author: "Bryan Stevenson" },
    { title: "The New Jim Crow", author: "Michelle Alexander" },
    { title: "Evicted", author: "Matthew Desmond" },
    { title: "Nickel and Dimed", author: "Barbara Ehrenreich" },
    { title: "The Immortalists", author: "Chloe Benjamin" },
    { title: "The Mothers", author: "Brit Bennett" },
    { title: "Homegoing", author: "Yaa Gyasi" },
    { title: "Less", author: "Andrew Sean Greer" },
    { title: "The Sellout", author: "Paul Beatty" }
];

/**
 * Selects a random book from the FAMOUS_BOOKS library
 * and populates the book entry form with it
 * This provides a default suggestion and inspiration for users
 */
export function setRandomDefaultBook() {
    const randomIndex = Math.floor(Math.random() * FAMOUS_BOOKS.length);
    const selectedBook = FAMOUS_BOOKS[randomIndex];

    const bookNameInput = document.getElementById('book-name');
    const authorNameInput = document.getElementById('author-name');

    if (bookNameInput && authorNameInput) {
        bookNameInput.value = selectedBook.title;
        authorNameInput.value = selectedBook.author;
    }
}
